spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/employees;AUTO_SERVER=true
    username: sa
    driver-class-name: org.h2.Driver
    sql-script-encoding: utf-8
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update

  batch:
    job:
      enabled: false

