DROP TABLE IF EXISTS TBL_SBERCLIENT;
DROP TABLE IF EXISTS TBL_USERS;
DROP TABLE IF EXISTS TBL_RAWTRANSACTIONS;
DROP TABLE IF EXISTS TBL_SBERACCOUNT;

--Таблица "Пользователи"
CREATE TABLE TBL_USERS (
     id INT AUTO_INCREMENT PRIMARY KEY,
     first_name VARCHAR(250) NOT NULL,
     last_name VARCHAR(250) NOT NULL,
     email VARCHAR(250) NOT NULL UNIQUE
);

--Таблица "Аккаунт пользователя"
CREATE TABLE TBL_SBERACCOUNT (
     id INT AUTO_INCREMENT PRIMARY KEY,
     account_name VARCHAR(250) NOT NULL UNIQUE,
     cash DOUBLE NOT NULL
);

--Таблица "СберКлиент"
CREATE TABLE TBL_SBERCLIENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL REFERENCES TBL_USERS(id),
    account_id INT NOT NULL REFERENCES TBL_SBERACCOUNT(id),
    constraint unq_sberclient unique(user_id, account_id)
);

--Таблица транзакций
CREATE TABLE TBL_RAWTRANSACTIONS
(
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_id INT NOT NULL REFERENCES TBL_SBERACCOUNT(id),
  income DOUBLE NOT NULL,
  cash DOUBLE NOT NULL,
  date_of_transaction DATETIME NOT NULL DEFAULT NOW()
);


